---
# Location where configuration files will be stored.
config_dir: '~'

# IPv6 configuration: You can specify your desired subnet for docker-compose here.
# If you change these settings, you must tear down any existing containers first so the network is created from scratch
docker_ipv6_enable: false
docker_ipv6_subnet: 2001:3984:3989::/64
docker_ipv6_gateway: 2001:3984:3989::1

# Domain names configuration (related services need to be enabled).
domain_name_enable: false
domain_name: 'home.local'
domain_pihole: 'pihole'          # to access pihole via: http://pihole.home.local
domain_grafana: 'grafana'        # to access grafana via: http://grafana.home.local
domain_prometheus: 'prometheus'  # to access prometheus via: http://prometheus.home.local

# Pi-hole configuration.
pihole_enable: true
pihole_hostname: pihole
pihole_timezone: America/Chicago
pihole_password: "change-this-password"

# Raspberry monitoring configuration
raspberry_monitoring_enable: false
telegraf_retention_policy: '90d'
telegraf_password: 'admin'

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin"
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.com/;google.com
  - https://github.com/;github.com
  - https://www.apple.com/;apple.com

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_plugs_enable: false
shelly_plugs:           # list of Shelly Plugs to connect to
  - name: my-shelly-plug   # will show up in dashboard to identify this plug
    hostname: "my-shelly-plug-host-or-ip"
    port: 9924
shelly_plugs_http_username: username
shelly_plugs_http_password: "password"

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: false
airgradient_sensors:
  # ID Should be limited to no more than 38 characters, in the set a-z.
  - id: livingroom
    ip: "192.168.0.123"
    port: 9925

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false
