---
- name: Restart pi-hole
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/pi-hole/"
    build: false
    restarted: true
  become: false

- name: Restart internet-monitoring
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/internet-monitoring/"
    build: false
    restarted: true
  become: false

- name: Restart shelly-plug-prometheus
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/shelly-plug-prometheus/"
    build: false
    restarted: true
  become: false

- name: Restart starlink-exporter
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/starlink-exporter/"
    build: false
    restarted: true
  become: false
